//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeCreatorWPF.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredient()
        {
            this.Recipe_Ingredient = new HashSet<Recipe_Ingredient>();
        }
    
        public int Ingredient_ID { get; set; }
        public string Name { get; set; }
        public byte[] IngredientImage { get; set; }
        public int FoodUnit_ID { get; set; }
        public int Weight { get; set; }
        public virtual FoodUnit FoodUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipe_Ingredient> Recipe_Ingredient { get; set; }
    }
}
