//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeCreatorWPF.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe_Ingredient
    {
        public int Recipe_Ingredient_ID { get; set; }
        public int Recipe_ID { get; set; }
        public int Ingredient_ID { get; set; }
        public int Weight { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
