//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeCreatorWPF.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.Recipe_Ingredient = new HashSet<Recipe_Ingredient>();
        }
    
        public int Recipe_ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] RecipeImage { get; set; }
        public int CookTime { get; set; }
        public int FoodType_ID { get; set; }
        public int User_ID { get; set; }
        public string CookMethod { get; set; }
        public Nullable<bool> isChecked { get; set; }
    
        public virtual FoodType FoodType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipe_Ingredient> Recipe_Ingredient { get; set; }
        public virtual User User { get; set; }
    }
}
